// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBawyb9E3D0wAyZIojdj5ja50S0t-I4ipQ',
    appId: '1:49033806908:web:5e61f7ecaa7cdc90506f39',
    messagingSenderId: '49033806908',
    projectId: 'cached-firestorage-demo',
    authDomain: 'cached-firestorage-demo.firebaseapp.com',
    storageBucket: 'cached-firestorage-demo.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAV8aN0RmpTfAhSzGAR4idwJcMbSfP-doU',
    appId: '1:49033806908:android:f0ef65d34beb6d3e506f39',
    messagingSenderId: '49033806908',
    projectId: 'cached-firestorage-demo',
    storageBucket: 'cached-firestorage-demo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByH1-GIho2Yn_yjZ3JrrSEiylpyZliB9A',
    appId: '1:49033806908:ios:153672555969b8f3506f39',
    messagingSenderId: '49033806908',
    projectId: 'cached-firestorage-demo',
    storageBucket: 'cached-firestorage-demo.appspot.com',
    iosClientId: '49033806908-phmvubta6q2867fi1s55ndebj6hsg806.apps.googleusercontent.com',
    iosBundleId: 'com.example.example',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyByH1-GIho2Yn_yjZ3JrrSEiylpyZliB9A',
    appId: '1:49033806908:ios:153672555969b8f3506f39',
    messagingSenderId: '49033806908',
    projectId: 'cached-firestorage-demo',
    storageBucket: 'cached-firestorage-demo.appspot.com',
    iosClientId: '49033806908-phmvubta6q2867fi1s55ndebj6hsg806.apps.googleusercontent.com',
    iosBundleId: 'com.example.example',
  );
}
